Ft new york times
kbjude/new-york-times pull request #3
Opened 2019-12-16 21:27 UTC by Eder-PG

Features branch for the New York Times project

Third project ready for submission
No HTML or CSS-Lint errors left

2019-12-16 22:17 UTC, pelzolga123 commented on index.html
> +                </svg>-->
Commented code should be removed.

2019-12-16 22:17 UTC, pelzolga123 commented on index.html
> +                        </svg>-->
Commented code should be removed.

2019-12-16 22:17 UTC, pelzolga123 commented on index.html
> +                        </svg>-->
Commented code should be removed.

2019-12-16 22:19 UTC, pelzolga123 requested changes
Logo and bottom part should have links. Readme file needs some correction. Pull request should be more descriptive.

2019-12-16 22:19 UTC, pelzolga123 commented
## Hi Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Your project looks :+1: amazing!

Here are some things, that require changes:

* [ ] Pull Request has meaningful title and a short description. You have some text in your pull request description section, but it is not the right one. Name should be changes as well to more descriptive. Correct pull request description should have list of things you implemented in this project. 
For example:

* Created fixed header and footer.
* Added embedded images and video.

Look at [this link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) from pathwright for detailed description.

* [ ] Readme file has 'HTML Forms' header. This header is from previous project, please change it.  

* [ ] In Navbar NY Times logo should be a link. [Link to original website](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)

* [ ] Bottom part should contain links to other articles on the leftmost side. [Link to original website](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)

* [ ] Bottom part should contain links to other articles on the rightmost side. [Link to original website](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)

* [ ] Footer should have a fixed position (it sticks to the bottom part of the screen):
![image](https://user-images.githubusercontent.com/20416431/70352647-43bdb300-1874-11ea-9d67-65dca68d961d.png)

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2019-12-17 00:07 UTC, Eder-PG commented
Thanks! I added all missing features and fixed oversights pointed by the review
Code is still free of HTML and CSS errors

2019-12-17 00:38 UTC, izaiasneto4 commented
# Hi folks :wave: 
Great work implementing the changes. Looks like you have everything. It's a yes for me :+1: 

Your project looks really good by the way :wink: 

You can merge the project and submit the project completion form :+1: :100:

2019-12-17 08:26 UTC, kbjude commented
Thank you Izaias,
Thats very encouraging.

On Tue, Dec 17, 2019 at 3:38 AM Izaias Neto <notifications@github.com>
wrote:

> Hi folks 👋
>
> Great work implementing the changes. Looks like you have everything. It's
> a yes for me 👍
>
> Your project looks really good by the way 😉
>
> You can merge the project and submit the project completion form 👍 💯
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kbjude/new-york-times/pull/3?email_source=notifications&email_token=AEBKXYC2YU35EKKO2PDXO6TQZANOZA5CNFSM4J3RLWX2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHAVDRQ#issuecomment-566317510>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEBKXYDFFF6MZTVZYKDM5I3QZANOZANCNFSM4J3RLWXQ>
> .
>

2019-12-17 08:27 UTC, merged